const synth = window.speechSynthesis;
let voices = [];
function loadVoices() { voices = synth.getVoices() || []; }
if ('speechSynthesis' in window) { loadVoices(); window.speechSynthesis.onvoiceschanged = loadVoices; }
function scoreAmericanVoice(v) {
  const name = (v.name || '').toLowerCase(); const lang = (v.lang || '').toLowerCase(); let score = 0;
  if (lang === 'en-us') score += 100;
  if (/en-in|india|indian/.test(lang + ' ' + name)) score -= 300;
  if (/en-gb|en-au|en-ca|en-za|british|australia|canada/.test(lang + ' ' + name)) score -= 80;
  if (/us english|american|united states/.test(name)) score += 60;
  if (/samantha|ava|allison|susan|tom|joelle|jenny|aria|guy|davis|tony|microsoft|google us english/.test(name)) score += 40;
  if (/natural|neural|premium|enhanced/.test(name)) score += 20;
  if (lang.startsWith('en')) score += 10;
  return score;
}
function pickVoice() { loadVoices(); if (!voices.length) return null; const ranked=voices.filter(v=>(v.lang||'').toLowerCase().startsWith('en')).map(v=>({voice:v,score:scoreAmericanVoice(v)})).sort((a,b)=>b.score-a.score); return (ranked.find(x=>x.score>0)||{}).voice || voices.find(v=>(v.lang||'').toLowerCase()==='en-us') || voices[0]; }
function speak(text, rate=0.82) { if (!('speechSynthesis' in window)) { alert('当前浏览器不支持朗读功能，请用 Chrome / Safari / Edge 打开。'); return; } synth.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='en-US'; u.rate=rate; u.pitch=1; u.volume=1; const v=pickVoice(); if(v) u.voice=v; synth.speak(u); }
document.querySelectorAll('[data-say]').forEach(btn=>btn.addEventListener('click',()=>speak(btn.dataset.say, btn.classList.contains('sentence')?0.76:0.82)));
document.getElementById('readAll')?.addEventListener('click',()=>{ const words=[...document.querySelectorAll('.word-card')].map(c=>c.dataset.word).join('. '); speak(words,0.72); });
document.getElementById('readExamples')?.addEventListener('click',()=>{ const examples=[...document.querySelectorAll('.word-card .sentence')].map(b=>b.dataset.say).join(' '); speak(examples,0.76); });
for (const id of ['pauseBtn','pauseReading']) document.getElementById(id)?.addEventListener('click',()=>synth.pause());
for (const id of ['resumeBtn','resumeReading']) document.getElementById(id)?.addEventListener('click',()=>synth.resume());
for (const id of ['stopBtn','stopReading']) document.getElementById(id)?.addEventListener('click',()=>synth.cancel());
document.getElementById('printBtn')?.addEventListener('click',()=>window.print());

const V7_KEY = 'SAT_DAY7_V7_EXAMPLE_PRACTICE_STATE';
const QUIZ_ANSWERS = ['B', 'A', 'B', 'A', 'B', 'C', 'A', 'B'];
const FILL_ANSWERS = ['cogent', 'coalesce', 'clemency', 'cliché', 'censure', 'composed', 'comply', 'charismatic', 'coercion', 'capricious'];
const READING_ANSWERS = ['charismatic', 'cogent', 'coalesce', 'circumspect', 'complacent', 'circumvent', 'caustic', 'composed'];
function normalizeAnswer(value) { return (value||'').trim().toLowerCase().replace(/[.,;:!?]+$/g,'').replace(/\s+/g,' '); }
function loadPracticeState() { try { return JSON.parse(localStorage.getItem(V7_KEY)) || {quiz:{}, fill:{}, reading:{}, details:{}}; } catch(e) { return {quiz:{}, fill:{}, reading:{}, details:{}}; } }
function savePracticeState(state) { localStorage.setItem(V7_KEY, JSON.stringify(state)); const status=document.getElementById('saveStatus'); if(status) status.textContent='已自动保存到本机 '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}); }
let practiceState = loadPracticeState();
function setupQuizClickable() { document.querySelectorAll('#quiz .question').forEach((q,qIndex)=>{ const ol=q.querySelector('ol'); if(!ol) return; ol.classList.add('choice-list'); [...ol.querySelectorAll('li')].forEach((li,optIndex)=>{ const letter=String.fromCharCode(65+optIndex); const text=li.textContent.trim().replace(/^([A-D]\.\s*)/,''); li.innerHTML=''; const btn=document.createElement('button'); btn.type='button'; btn.className='choice-btn'; btn.dataset.question=String(qIndex); btn.dataset.choice=letter; btn.innerHTML=`<span class="choice-letter">${letter}</span><span>${text}</span>`; btn.addEventListener('click',()=>{ practiceState.quiz[qIndex]=letter; savePracticeState(practiceState); renderQuizState(qIndex); }); li.appendChild(btn); }); const feedback=document.createElement('div'); feedback.className='practice-feedback'; feedback.id=`quiz-feedback-${qIndex}`; q.appendChild(feedback); renderQuizState(qIndex); }); }
function renderQuizState(qIndex) { const q=document.querySelectorAll('#quiz .question')[qIndex]; if(!q) return; const selected=practiceState.quiz[qIndex]; const correct=QUIZ_ANSWERS[qIndex]; q.querySelectorAll('.choice-btn').forEach(btn=>{ btn.classList.remove('selected','correct','wrong'); if(btn.dataset.choice===selected) { btn.classList.add('selected'); btn.classList.add(selected===correct?'correct':'wrong'); } }); const fb=document.getElementById(`quiz-feedback-${qIndex}`); if(fb) { if(!selected) fb.textContent=''; else fb.textContent= selected===correct?'✓ 回答正确，已保存。':'✗ 已保存。可以再选一次，或点“显示答案”核对。'; fb.className='practice-feedback '+(selected?(selected===correct?'ok':'no'):''); } }
function addInputPractice(sectionSelector, answers, bucketName, placeholder) { document.querySelectorAll(`${sectionSelector} .question`).forEach((q,i)=>{ if(q.querySelector('.practice-input-row')) return; const row=document.createElement('div'); row.className='practice-input-row'; row.innerHTML=`<input class="practice-input" type="text" autocomplete="off" placeholder="${placeholder}" data-bucket="${bucketName}" data-index="${i}"><button type="button" class="check-one">检查</button><span class="practice-feedback"></span>`; const details=q.querySelector('details.answer'); q.insertBefore(row, details||null); const input=row.querySelector('input'); const btn=row.querySelector('button'); const fb=row.querySelector('.practice-feedback'); input.value=practiceState[bucketName]?.[i]||''; function saveAndMaybeCheck(showFeedback=false) { practiceState[bucketName][i]=input.value; savePracticeState(practiceState); if(showFeedback) { const user=normalizeAnswer(input.value); const correct=normalizeAnswer(answers[i]); const ok=user===correct; input.classList.toggle('correct', ok&&!!user); input.classList.toggle('wrong', !ok&&!!user); fb.textContent=!user?'请输入答案。':(ok?'✓ 回答正确，已保存。':'✗ 已保存。可修改后再检查，或点“显示答案”核对。'); fb.className='practice-feedback '+(ok?'ok':'no'); } else { input.classList.remove('correct','wrong'); fb.textContent=input.value?'已保存':''; fb.className='practice-feedback'; } } input.addEventListener('input',()=>saveAndMaybeCheck(false)); input.addEventListener('keydown',e=>{ if(e.key==='Enter') saveAndMaybeCheck(true); }); btn.addEventListener('click',()=>saveAndMaybeCheck(true)); }); }
function setupDetailsSave() { document.querySelectorAll('details.answer').forEach((d,i)=>{ const key=`answer-${i}`; if(practiceState.details&&practiceState.details[key]) d.open=true; d.addEventListener('toggle',()=>{ practiceState.details=practiceState.details||{}; practiceState.details[key]=d.open; savePracticeState(practiceState); }); }); }
function checkAllPractice() { Object.keys(practiceState.quiz||{}).forEach(k=>renderQuizState(Number(k))); document.querySelectorAll('.practice-input-row .check-one').forEach(btn=>btn.click()); }
function resetPractice() { const ok=confirm('确定要清除 Day7 本机做题记录吗？选择题、输入内容、颜色和已展开答案都会恢复为空白。'); if(!ok) return; localStorage.removeItem(V7_KEY); practiceState={quiz:{}, fill:{}, reading:{}, details:{}}; document.querySelectorAll('.choice-btn').forEach(btn=>btn.classList.remove('selected','correct','wrong')); document.querySelectorAll('.practice-input').forEach(input=>{input.value=''; input.classList.remove('correct','wrong');}); document.querySelectorAll('.practice-feedback').forEach(fb=>{fb.textContent=''; fb.className='practice-feedback';}); document.querySelectorAll('details.answer').forEach(d=>d.open=false); const mode=document.getElementById('practiceMode'); if(mode){mode.value='all'; applyPracticeMode('all');} const status=document.getElementById('saveStatus'); if(status) status.textContent='记录已清除，可以重新开始。'; }
function applyPracticeMode(mode) { const map={words:'#words', quiz:'#quiz', fill:'#fill', reading:'#reading'}; ['#words','#quiz','#fill','#reading'].forEach(sel=>{ const el=document.querySelector(sel); if(!el) return; if(mode==='all'||map[mode]===sel) el.classList.remove('hidden-section'); else el.classList.add('hidden-section'); }); if(mode!=='all'&&map[mode]) document.querySelector(map[mode])?.scrollIntoView({behavior:'smooth',block:'start'}); }
function initV7Practice() { setupQuizClickable(); addInputPractice('#fill',FILL_ANSWERS,'fill','输入填空答案'); addInputPractice('#reading',READING_ANSWERS,'reading','输入阅读找词答案'); setupDetailsSave(); document.getElementById('resetPractice')?.addEventListener('click',resetPractice); document.getElementById('checkAllBtn')?.addEventListener('click',checkAllPractice); document.getElementById('practiceMode')?.addEventListener('change',e=>applyPracticeMode(e.target.value)); }
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',initV7Practice); else initV7Practice();
